#!/usr/bin/env python
# encoding: utf-8

# wscript in ./test

import os

# ************************************************************************ build
def build(bld):
    print('→ build from ' + bld.path.abspath())

    # -------------------------------------------------------------------- ImGUI
    ## build list of ImGUI sources
    imgui_dir = "../libs/imgui/"
    imgui_files = [ "imgui.cpp",
                    "imgui_draw.cpp",
                    "imgui_tables.cpp",
                    "imgui_widgets.cpp",
                    "imgui_demo.cpp",
    ]
    imgui_backend = [ "backends/imgui_impl_glfw.cpp",
                      "backends/imgui_impl_opengl3.cpp",
    ]
    imgui_sources = [imgui_dir+path for path in imgui_files+imgui_backend]

    # ---------------------------------------------------------- ImGuiFileDialog
    ## build list of ImGuiFileDialog sources
    imguifile_dir = "../libs/ImGuiFileDialog/"
    imguifile_files = [ "ImGuiFileDialog.cpp"
    ]
    imguifile_sources = [imguifile_dir+path for path in imguifile_files]

    # ------------------------------------------------------------------- ImPlot
    ## build list of ImGUI sources
    implot_dir = "../libs/implot/"
    implot_files = [ "implot.cpp",
                    "implot_items.cpp",
    ]
    implot_sources = [implot_dir+path for path in implot_files]

    # ------------------------------------------------------------------  docopt
    docopt_dir = "../libs/docopt.cpp/"
    docopt_files = [ "docopt.cpp",
    ]
    docopt_sources = [docopt_dir+path for path in docopt_files]
    
    bld.objects(
        source = docopt_sources,
        target = "docopt.obj",
        use = ["DOCOPT"]
    )
    
    def build_file( file ):
        print( "** Buildind "+file )
        bld.program(
            source =   [file] + imgui_sources + implot_sources,
            target =   file[:-4],
            includes = [".", "../src", imgui_dir, imgui_dir+"backends/",
                        imguifile_dir],
            lib =     ['X11','Xss'],#["m","rt","dl"], # X11 screensaver
            use =      [# "DOCOPT", "docopt.obj",
                        "IMGUI",
                        # "IMGUIFILEDIALOG",
                        "IMPLOT",
                        "MINIAUDIO",
                        "GLFW3", "GL",
                        "X11", "XEXT"]
        )

    # base_files = ["04-leds_widget.cpp", "04-date_widget.cpp", "drum_compagnon.cpp"]
    # base_files = ["00-engine-play.cpp", "04-file_widget.cpp",
    #               "10-miniaudio-base.cpp",
    #               "11-simple-innerloop.cpp",
    #               "12-waveform-gui.cpp",
    #               "drum_compagnon.cpp", "big_clock.cpp"]
    base_files = [ # "drum_compagnon.cpp", "big_clock.cpp",
                   "12-waveform-gui.cpp",
                 ]
    for file in base_files:
        build_file( file )
        
    # check test option
    if bld.options.test:
        # detect all *test* files that should be build
        for file in os.listdir( bld.path.abspath() ):
            # only .cpp files beginning with number
            if file.endswith(".cpp") and file[:1].isdigit():
                build_file( file )

    
