#!/usr/bin/env python
# encoding: utf-8

# wscript in ./test

import os

# ************************************************************************ build
def build(bld):
    print('→ build from ' + bld.path.abspath())

    # -------------------------------------------------------------------- ImGUI
    ## build list of ImGUI sources
    imgui_dir = "../libs/imgui/"
    imgui_files = [ "imgui.cpp",
                    "imgui_draw.cpp",
                    "imgui_tables.cpp",
                    "imgui_widgets.cpp",
    ]
    imgui_backend = [ "backends/imgui_impl_glfw.cpp",
                      "backends/imgui_impl_opengl3.cpp",
    ]
    imgui_sources = [imgui_dir+path for path in imgui_files+imgui_backend]

    # ------------------------------------------------------------------  docopt
    docopt_dir = "../libs/docopt.cpp/"
    docopt_files = [ "docopt.cpp",
    ]
    docopt_sources = [docopt_dir+path for path in docopt_files]
    
    bld.objects(
        source = docopt_sources,
        target = "docopt.obj",
        use = ["DOCOPT"]
    )
    
    def build_file( file ):
        print( "** Buildind "+file )
        bld.program(
            source =   [file] + imgui_sources,
            target =   file[:-4],
            includes = [".", "../src", imgui_dir, imgui_dir+"backends/"],
            libs =     [],#["m","rt","dl"],
            use =      ["DOCOPT", "docopt.obj",
                        "IMGUI",
                        "MINIAUDIO",
                        "GLFW3", "GL"]
        )

    base_files = ["04-leds_widget.cpp", "04-date_widget.cpp", "drum_compagnon.cpp"]
    for file in base_files:
        build_file( file )
        
    # check test option
    if bld.options.test:
        # detect all *test* files that should be build
        for file in os.listdir( bld.path.abspath() ):
            # only .cpp files beginning with number
            if file.endswith(".cpp") and file[:1].isdigit():
                build_file( file )

    
