#!/usr/bin/env python
# encoding: utf-8

# wscript in ./test

import os

# ************************************************************************ build
def build(bld):
    print('→ build from ' + bld.path.abspath())

    # -------------------------------------------------------------------- ImGUI
    ## build list of ImGUI sources
    imgui_dir = "../libs/imgui/"
    imgui_files = [ "imgui.cpp",
                    "imgui_draw.cpp",
                    "imgui_tables.cpp",
                    "imgui_widgets.cpp",
    ]
    imgui_backend = [ "backends/imgui_impl_glfw.cpp",
                      "backends/imgui_impl_opengl3.cpp",
    ]
    imgui_sources = [imgui_dir+path for path in imgui_files+imgui_backend]

    # ---------------------------------------------------------------- 00-button
    bld.program(
        source =   ["00-button.cpp"] + imgui_sources,
        target =   "00-button",
        includes = [".", imgui_dir, imgui_dir+"backends/"],
        libs =     [],#["m","rt","dl"],
        use =      ["GLFW3", "GL"]
    )
    # ------------------------------------------------------------ 01-play-pause
    bld.program(
        source =   ["01-play-pause.cpp"] + imgui_sources,
        target =   "01-play-pause",
        includes = [".", imgui_dir, imgui_dir+"backends/"],
        libs =     [],#["m","rt","dl"],
        use =      ["MINIAUDIO", "GLFW3", "GL"]
    )

    # ----------------------------------------------------------- 00-engine-play
    bld.program(
        source =   ["00-engine-play.cpp"],
        target =   "00-engine-play",
        includes = ["."],
        libs =     [], #["-ldl -lm -lpthread
        use =      ["MINIAUDIO"]
    )
    # ---------------------------------------------------------- 01-sound-repeat
    bld.program(
        source =   ["01-sound-repeat.cpp"],
        target =   "01-sound-repeat",
        includes = ["."],
        libs =     [], #["-ldl -lm -lpthread
        use =      ["MINIAUDIO"]
    )
    # --------------------------------------------------------- 02-audio-pattern
    bld.program(
        source =   ["02-audio-pattern.cpp"],
        target =   "02-audio-pattern",
        includes = [".", "../src"],
        libs =     [], #["-ldl -lm -lpthread
        use =      []
    )

    
